apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webmethods-sample-apis.fullname" . }}
  labels:
    {{- include "webmethods-sample-apis.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "webmethods-sample-apis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "webmethods-sample-apis.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "webmethods-sample-apis.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if .Values.image.registry }}
          image: {{ printf "%s/%s:%s" .Values.image.registry .Values.image.repository (.Values.image.tag | default .Chart.AppVersion) }}
          {{- else }}
          image: {{ printf "%s:%s" .Values.image.repository (.Values.image.tag | default .Chart.AppVersion) }}
          {{- end }}        
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.appPort }}
          livenessProbe:
            httpGet:
              path: {{ printf "%s/%s" .Values.appContextPath .Values.appHealthCheckPath }}
              port: {{ .Values.appPort }}
              {{- with .Values.appHealthCheckHeaders }}
              httpHeaders:
                {{- toYaml . | nindent 16 }}
              {{- end }}
            {{- with .Values.livenessProbe }}
            successThreshold: {{ .successThreshold }}
            failureThreshold: {{ .failureThreshold }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.appPort }}
            - name: app_port
              value: {{ .Values.appPort | quote }}
            {{- end }} 
            {{- if .Values.appContextPath }}
            - name: app_context_path
              value: {{ .Values.appContextPath | quote }}
            {{- end }} 
            {{- if .Values.appHealthCheckPath }}
            - name: app_healthcheck_path
              value: {{ .Values.appHealthCheckPath | quote }}
            {{- end }} 
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        {{ with .Values.microgateway }}
        {{- if .enabled }}
        - name: {{ $.Chart.Name }}-mgw
          {{- if .image.registry }}
          image: {{ printf "%s/%s:%s" .image.registry .image.repository (.image.tag | default $.Chart.AppVersion) }}
          {{- else }}
          image: {{ printf "%s:%s" .image.repository (.image.tag | default $.Chart.AppVersion) }}
          {{- end }} 
          imagePullPolicy: {{ .image.pullPolicy }}
          {{- with .commandArgs }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            {{- if .port }}
            - containerPort: {{ .port }}
              name: rtport
              protocol: TCP
            {{ end }}
            {{- if .portSSL }}
            - containerPort: {{ .portSSL }}
              name: rtportssl
              protocol: TCP
            {{ end }}
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            exec:
              command:
              - /bin/sh
              - -c
              - ./files/k8s-lifenesscheck.sh
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            exec:
              command:
              - /bin/sh
              - -c
              - ./files/k8s-readinesscheck.sh
          {{- with .resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- if .port }}
            - name: PORT_RUNTIME
              value: {{ .port | quote }}
            {{ end }}
            {{- if .portSSL }}
            - name: PORT_RUNTIME_SSL
              value: {{ .portSSL | quote }}
            {{ end }}
            {{- if .logLevel }}
            - name: LOGS_LEVEL
              value: {{ .logLevel | quote }}
            {{ end }}
            - name: mcgw_api_endpoint_access_url   # specify the accessible microgateway address
              value: http://{{ include "webmethods-sample-apis.fullname" . }}:{{ .Values.service.port }}
            - name: CUSTOM_SETTINGS
              value: "/configs/microgateway.yml"
            {{- with .env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            {{- if .configs }}
            - name: mgw-configs-volume
              mountPath: /configs
            {{- end }}
            {{- with .licenseSecret }}
            - name: mgw-license
              mountPath: /opt/softwareag/config/license.xml
              subPath: {{ .path }}
              readOnly: false
            {{- end }}
            {{- if .archivesConfigMap }}
            - name: mgw-archives
              mountPath: /opt/softwareag/archives
            {{- end }}
        {{- end }}
        {{- end }}
      volumes:
      {{- $uname := (include "webmethods-sample-apis.fullname" .) }}
      {{ with .Values.microgateway }}
      {{- if .enabled }}
      {{- if .configs }}
      - name: mgw-configs-volume
        configMap:
          name: {{ $uname }}-mgw
      {{- end }}
      {{- with .licenseSecret }}
      - name: mgw-license
        secret:
          secretName: {{ .name }}
          items:
          - key: {{ .key }}
            path: {{ .path }}
      {{- end }}
      {{- if .archivesConfigMap }}
      - name: mgw-archives
        configMap:
          name: {{ .archivesConfigMap }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}